### ISSUE TITLE
[FR] Add argument file support to build_zip

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_pkg#245]
`build_tar` has support for argument file, but `build_zip` does not. It would be a nice feature to have since without this, we wouldn’t be able to create a zip from a lot of files due to the command line argument length limit.

**Comment by aiuto** [comment]
This sounds like a bug more than a feature request. Is it fair to restate it as
"pkg_zip fails for large numbers of input files"?

How it gets solved is an implementation detail. When we move to pkg_filegroup, the list of source targets and where they go in the zip is going to be it's own file anyway, so that will sidestep the question of using argument files or not.

**Comment by thii** [comment]
Closing since it looks like it works as expected. Sorry for the confusion.
