### ISSUE TITLE
Improve pkg_zip

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_pkg#30]
Some requirements:
- portable to *nix & Windows without forking the system zip
- ability to repath files to where you want them
- ability to set permissions per file
- tests that run on all platforms

**Comment by j3parker** [comment]
Is a python implementation along the lines of `pkg_tar` acceptable?

**Comment by aiuto** [comment]
Yes. We should aim for cross OS portability first, and then we can iterate towards faster.
Are you thinking of taking this on? It would be great to have a design proposal for how to handle re-pathing files and permissions. Ideally, the same mechanism should eventually work for pkg_{tar, deb, rpm, ...} too.

On Monday I can extract the docs for the rules Google uses internally for mapping files into packages into a doc to use as an example of requirements. The actual rules we use have sort of grown into a mashup of competing implementations and ideas, so I would not want to bring them forward directly. The do, however, capture a lot of the corner cases.

**Comment by j3parker** [comment]
Ok. I'd be interesting in taking it on if that's helpful (I saw the "help wanted" tag). Portability is important for me because my company would need it to run on Windows and Linux :) (and I have a Mac).

A design proposal sounds great. Would you like to see that done via https://github.com/bazelbuild/proposals ? Or another way? You mentioned the proposal RE: repathing/permissions. Would the proposal be specific to that or would it be a proposal for `pkg_zip`, including those aspects? Should the proposal consider pkg_{tar, deb,rpm, ...} as well in that context?

I understand what you mean by repathing and permissions at a high level, but any extra docs/context you could provide would be great, especially for corner cases. As an outsider, nothing comes to mind ;)

Something personally I'd want to nail down early is the contract for the rule in detail. That could be done in a design proposal and/or in a small PR (with `pkg_zip = rule( ... )`  (basically, the attrs) + an impl that is just `# TODO` to a branch. If you like getting things in `master` then maybe it could initially be `_pkg_zip`). I could also paste a gist to this issue instead.

More generally I'd be interested in doing it in a sequence of smaller PRs (either into master or a branch). The benefits to this would be it'd be easier for someone else to pick up the work if I couldn't finish it and (I find) it's easier to review. If you'd rather have one PR with the full implementation (after a design proposal), though, that's fine too.

**Comment by aiuto** [comment]
On Sat, Jul 20, 2019 at 12:07 PM Jacob Parker <notifications@github.com>
wrote:

> Ok. I'd be interesting in taking it on if that's helpful (I saw the "help
> wanted" tag). Portability is important for me because my company would need
> it to run on Windows and Linux :) (and I have a Mac).
>
> A design proposal sounds great. Would you like to see that done via
> https://github.com/bazelbuild/proposals ? Or another way?
>
Yes. Proposals is the right way. Proposals are for the entire Bazel
community, not just bazel core.


> You mentioned the proposal RE: repathing/permissions. Would the proposal
> be specific to that or would it be a proposal for pkg_zip, including
> those aspects? Should the proposal consider pkg_{tar, deb,rpm, ...} as well
> in that context?
>
They are all in context. People who build .deb files want to be able to
reuse the same infrastructure for creating an RPM.
And all of tar, zip, deb, rpm files need path remapping.


> I understand what you mean by repathing and permissions at a high level,
> but any extra docs/context you could provide would be great, especially
> for corner cases. As an outsider, nothing comes to mind ;)
>
I took the docs for the packaing rules Google uses and made them available
here.
https://docs.google.com/document/d/13clxLvBE3iEpm7eAZpiKZa_TJ0xG3LmYaJrOmwZt7l4/edit#heading=h.5mcn15i0e1ch

There is a lot of power, and some very confusing syntax.

> Something personally I'd want to nail down early is the contract for the
> rule in detail. That could be done in a design proposal and/or in a small
> PR (with pkg_zip = rule( ... ) (basically, the attrs) + an impl that is
> just # TODO to a branch. If you like getting things in master then maybe
> it could initially be _pkg_zip). I could also paste a gist to this issue
> instead.
>
A basic pkg_zip rule that works like pkt_tar would be fine to start with.
If it emulated pkg_tar and was portable to Windows, that would be better
than not having anything.  We can work on path mapping after that. What I
wanted to avoid was doing path mapping differently for every package type,
or having to have it ripple to many other Bazel rules.

More generally I'd be interested in doing it in a sequence of smaller PRs
> (either into master or a branch). The benefits to this would be it'd be
> easier for someone else to pick up the work if I couldn't finish it and (I
> find) it's easier to review. If you'd rather have one PR with the full
> implementation (after a design proposal), though, that's fine too.
>
We always work in branches and then merge to master. We use the same
workflow as the rest of Bazel

   - https://github.com/bazelbuild/rules_pkg
   - Click the Fork icon in the upper right corner.
   - Make the fork  *YOUR_ID*/rules_pkg NOT bazlebuild/*YOUR_ID*/bazelbuild,
   as some github docs say.
   - It is easier to type
      - It does not clutter the rules_pkg repo with people's private
      branches

Use the "cross fork" PR flow on github. After the review is complete, I can
merge directly to master.

**Comment by j3parker** [comment]
Thanks for the link! It looks very interesting; not what I would have come up with from scratch :)

I'll work on a proposal and a basic `pkg_zip` concurrently. I'll keep that as simple as possible to avoid any API churn when the remapping stuff lands. Would it be better to omit `strip_prefix`/`mode`/etc. functionality that overlaps with `pkg_directory`/`pkg_library` etc.?

**Comment by aiuto** [comment]
Closing this since we now have pkg_zip at basic parity with the others.
