### ISSUE TITLE
pkg_deb supports pkg_filegroup framework

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#311]
The idea is that we could take a `srcs` list of inputs instead of a tar file as `data`.
Instead of having two actions, one to build the .tar and the second to make the .deb from it, we would have a single on which builds a synthetic tar directly from the inputs.  This would save a copy.

**Comment by aiuto** [comment]
I looked into this a bit and decided that it is not worth the effort at this time.
- We would want to add any tar compression controls to the pkg_deb attributes.
- make_deb.py increases in complexity a lot, with duplicated work from build_tar.

The way I might approach this is to first refactor build_tar and build_zip
- create a helper library that reads the manifest and does a callback to stream input files to the calling context
- rewrite zip and tar to use the helper
- refactor build_tar so that it can write to a stream instead of an actual file. Make that code a library
- finally, refactor make_deb to use the new helper and tar writer library to stream the inputs to a tar stream, and stuff that into the .deb file.

I can see the value of the refactoring, but this is not a 1.0 release blocker.

**Comment by aiuto** [comment]
Closing because I will never get around to this and no one has said it is needed for them.
