### ISSUE TITLE
Potential rules to be added here

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/rules_pkg#4]
### From https://github.com/GoogleCloudPlatform/distroless:

https://github.com/GoogleCloudPlatform/distroless/tree/master/package_manager

- package_manager_repositories
- dpkg_src
- dpkg_list

& their python helper tool

### From https://docs.bazel.build/versions/master/be/pkg.html:

- pkg_tar
- pkg_deb
- pkg_rpm

Seems like pkg_zip is also in the works at Google? pkg_chocolatey for Windows users for example might also be nice to have.

## General remarks

I personally would define a "package" as something that is typically not executable (even with an external runtime) on its own, a docker image for example is already right at the border between executable and package, while https://github.com/google/subpar clearly creates executables, not packages (even though it "packages" together various python libraries in the process) and a zip file is clearly a package, not an executable.

**Comment by aiuto** [comment]
I have started this process with pr #26 (which just reorganizes the repo a bit)

Also, I agree that "package" means not a binary. But... there are some binaries which include a self-extracting archive package. Those are still binaries rather than packages, but the rules to create them might heavily borrow from rules_pkg.  I am not adverse to "self_extracting_zip" being part of rules_pkg 
but I would be concerned about packaging that brings in a language runtime.

**Comment by MarkusTeufelberger** [comment]
Yeah, thanks for taking the initiative!

I agree that some package formats might be (also) executable on their own or with minimal tooling and once you start poking at edge cases it can get quite hard to define what they are (is an self-extracting archive more an archive or more a specialized `unzip` binary?). This was just my first try to define it somewhat consistently, of course there will always be edge cases too.

**Comment by aiuto** [comment]
Closing.  The pkg_ rules are added. There is little interest in adding more dpkg consuming rules here.
