### ISSUE TITLE
pkg_tar remap_paths doesn't remap tree artifacts

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/rules_pkg#450]
I appreciate that `remap_paths` is in the process of being deprecated but in my case the runfiles of a target that I am packaging contains a tree artifact and I want to remap its location.

The fix is to pass dest in the tree artifact branch through `_remap`.

**Comment by nacl** [comment]
What's the main problem here, the lack of runfiles support, or issues with TreeArtifacts?  Both?  I haven't quite taken a look at your proposed change yet.

WRT runfiles, they are going to be tricky to get right, since there isn't exactly a super clear dichotomy of what's (not) needed.  I know I haven't done any research into this, but @aiuto might have at some point more recently.  Related: #153.

WRT TreeArtifacts, the equivalent functionality for the `pkg_filegroup` framework has been proposed in #476.  I do not have an ETA for its completion.

**Comment by jnowjack-lucidchart** [comment]
We've started migrating our code to use `rules_pkg` in order to upgrade to Bazel 6 and we're running into this issue. We have a custom rule that declares a directory as an output and we'd like to remap it when using `pkg_tar`. Is there any workaround for this? Is there a reason that the `_remap` in [tar.bzl](https://github.com/bazelbuild/rules_pkg/blob/0.9.1/pkg/private/tar/tar.bzl#L139-L149) can't be pulled up outside of the `if f.is_directory:`?

**Comment by jsharpe** [comment]
Fixed in #738
