### ISSUE TITLE
Setting tags does not impact the execution of rules_pkg rules.

### ISSUE THREAD

**Issue by twheys** [bazelbuild/rules_pkg#504]
Hi,

I am using `pkg_tar` and I would like to set the bazel tag `no-remote-cache` to avoid caching the tar build result. The `tags` attribute is a built-in from Bazel and it is possible to set `tags = ["no-remote-cache"]` on the `pkg_tar` rule, however setting this value does not appear to have any impact. When building the target, the Bazel status line still reads `remote cache, multiplex worker`

It seems like that the `execution_requirements` attribute on Bazel `ctx.actions.run` needs to be set with the values from tags like 
```
execution_requirements = {
    "no-remote-cache": "1",
}
```

**Comment by aiuto** [comment]
Why are trying not to get cached results? That is one of bazel's strong points, that we cache what should not be rebuilt.
So, perhaps you have a different need, like trying to make it rebuild all the time, in which case stamp might help

In any case, tags have a specific meaning to people, and it is not execution requirements.  We would not want to subvert that to set an orthogonal feature.

**Comment by mzeren-vmw** [comment]
A multi-GB tar that changes frequently (because it tars up all build outputs) may not be worth caching. It may be globally faster to always tar and never wait to PUT or GET a cached copy. Empirically, we have many of these.

**Comment by twheys** [comment]
As far as I understand `tags` and `execution_requirements`, they are practically the same thing. The documentation for `execution_requirements` even links to tags for valid possible options.

A lot of the tags don't apply to a rule like `pkg_tar`, but my intention here was to create a generalized way to set the execution requirements. If you would prefer, I could change it to have an attribute that allows specific tags to be set like `no-cache`, `no-remote-cache`, etc.

**Comment by aiuto** [comment]
Tags are not really execution requirements. It is just that we happened to special case some tags change the action environment before execution requirements existed.  Thus the sort of mashup of use cases in the docs, plus the common use cases without examples. For example, many people use tag filters to limit what gets built/tested in ... expansions.

Filtering the set to specific ones is a start, but I really want to understand if we should fix this in Bazel overall before adding a hack here.  To be clear, "fix this in Bazel" may mean nothing more than creating a roadmap and guidance that declares we should use tags to specify exec requirements and it is up to users to avoid meaning clashes, or possibly that rules should declare an execution_requirements string list attribute that forwards to actions. That is, maybe your PR is conceptually fine, but would use a new attribute name rather than tags. I want to do a little research into this.

**Comment by nacl** [comment]
While I agree that there is something in bazel that needs to be fixed (`tags` is heavily overloaded), I believe there is an effective workaround in the form of the `--experimental_allow_tags_propagation` flag, which seems to propagate (at least some of the) tags to the execution_requirements of actions in starlark rules.  We have been using this internally to great effect.

If that flag does the right thing for this use case, I feel that we don't need to make any changes to rules_pkg to support this until more changes are made in bazel itself.

See also [documentation](https://docs.bazel.build/versions/main/command-line-reference.html#flag--experimental_allow_tags_propagation).
