### ISSUE TITLE
Synchronize documentation with upstream

### ISSUE THREAD

**Issue by kurt-google** [bazelbuild/rules_pkg#604]
It appears that pkg_tar supports a `compressor` argument these days, but this is not visible to users because its not documented where users might expect such as https://docs.bazel.build/versions/main/be/pkg.html#pkg_tar

However there is some documentation within the repository about this functionality. It would be nice if these were synchronized.

**Comment by kurt-google** [comment]
I should also note the "docs" link upstream is also broken.

**Comment by aiuto** [comment]
https://docs.bazel.build/versions/main/be/pkg.html#pkg_tar is not the documentation for this package. That one clearly says deprecated at the top and it points you back to rules_pkg.

What I can do is remove [ps://docs.bazel.build/versions/main/be/pkg.html](https://docs.bazel.build/versions/main/be/pkg.html), because no one should be using it.
