### ISSUE TITLE
pkg_deb does not set version in filename if version is set via `version_file`

### ISSUE THREAD

**Issue by msiebuhr** [bazelbuild/rules_pkg#658]
I use `version_file` to generate a per-commit version number (yay for stamping!), but that doesn't show up in the filename, which then ends up with `NAME__ARCH.deb` instead of `NAME_VERSION_ARCH.deb`.

If I use `version = "abc"`, I correctly get `NAME_abc_ARCH.deb`.

This has caused a few headaches for me, as it turned out our in-house repository de-duplicated things based on filenames...

For reference, I do roughly:

```bazel
def internal_deb(name, **kwargs):
   if not ("version" in kwargs or "version_file" in kwargs):
     kwargs["version_file"] = "//internals:canonical-release-tag"

  ...
  pkg_deb(name, **kwargs)
```

Also mentioned in https://github.com/bazelbuild/rules_pkg/issues/521#issuecomment-1288040803, but having spent better part of a day figuring this out, I feel the problem is entitled to it's very own issue :)

**Comment by aiuto** [comment]
It's not possible to get the filename based on the content of another file. That's a fundamental Bazel constraint because the build graph, including all output file names, is precomputed before the actions are executed. If the file with the version is written by Bazel, you have a loop.

My suggestion would be to wrapper git (or whatever SCM you use) to update a bit of starlark code like 'commit.bzl' with the current commit hash.   You can read that from your rules and build the file name from that.

**Comment by msiebuhr** [comment]
Yeah. I pretty much came to the same conclusion on the train homewards.

I'm currently trying to bake it into my dput-wrapper (which then re-names the files to have the right names + fixes the changes-file; not super-pretty, but it does work).
