### ISSUE TITLE
Make duplicate output paths an error instead of a warning

### ISSUE THREAD

**Issue by matts1** [bazelbuild/rules_pkg#682]
pkg_tar can detect when there are file conflicts ([code](https://github.com/bazelbuild/rules_pkg/blob/3b8e3f150fb83bb6098298c2a79011fd0b7d6a3f/pkg/private/pkg_files.bzl#L70-L84)). However, when it detects them, it prints them instead of failing. I see no reason why anyone would want it on `print` other than for backwards compatibility (which I assume is why it was first added), but if anyone can think of a reason, please tell me.

I'm happy to implement this myself. However, there  are a few ways we could do it, and I don't know what the best approach would be to take. I was looking for approval / feedback on the best approach to take.

Option 1: Simple cutoff
Change `print` to `fail`, and maybe increment the major version to indicate backwards incompatible changes. Alternatively, we may consider waiting for a major version increase to do this.

Option 2: Feature flag
Create a bool_flag that controls whether it prints or fails. Initially default it to false, and when we release other backwards incompatible changes, we can set it to true.

**Comment by aiuto** [comment]
Agreed. It should fail, and it only prints a warning for backwards compatibility with bad use cases. I am happy to go with option 2, but with a rule attribute rather than fail as the default.  
`allow_duplicates_with_different_content=False`. That name nicely hints that you are asking for something bad if you set it true.  On fail, the messages can say what attribute to add.

I think the backwards compatibility problem is not as bad as it could be. There are a lot of dups, but for the same source file.  Few people are doing sophisticated attribute rewrites and also having dups.  If a large organization really needs a global default change, they can vendor in the rules and fix it there.

We'll do the next release as 0.9.0.
