### ISSUE TITLE
pkg_rpm "cannot stat" data files in 0.2.2

### ISSUE THREAD

**Issue by apt-itude** [bazelbuild/rules_pkg#86]
Given a `BUILD` file such as the following:
```
load("@rules_pkg//:rpm.bzl", "pkg_rpm")

pkg_rpm(
    name = "fake-package",
    architecture = "x86_64",
    data = ["//src:test.txt"],
    version = "0.1.0",
    release = "0",
    spec_file = "fake-package.spec",
)
```
and a spec file such as:
```
Summary: Fake package for testing
Name: fake-package
Version: 0.1.0
Release: 0
License: MIT

%description
A fake package that lets me test stuff

%install
install -d -m 0755 %{buildroot}/etc
install -m 0755 {test.txt} %{buildroot}/etc

%files
/etc/test.txt
```

the following error is produced by `rpmbuild`:
```
Error calling rpmbuild:
Executing(%install): /bin/sh -e /tmp/tmpiUpfJr/TMP/rpm-tmp.8Xjyu0
+ umask 022
+ cd /tmp/tmpiUpfJr/BUILD
+ '[' /tmp/tmpiUpfJr/BUILD '!=' / ']'
+ rm -rf /tmp/tmpiUpfJr/BUILD
++ dirname /tmp/tmpiUpfJr/BUILD
+ mkdir -p /tmp/tmpiUpfJr
+ mkdir /tmp/tmpiUpfJr/BUILD
+ install -d -m 0755 /tmp/tmpiUpfJr/BUILD/etc
+ install -m 0755 src/test.txt /tmp/tmpiUpfJr/BUILD/etc
install: cannot stat 'src/test.txt': No such file or directory
error: Bad exit status from /tmp/tmpiUpfJr/TMP/rpm-tmp.8Xjyu0 (%install)


RPM build errors:
    Bad exit status from /tmp/tmpiUpfJr/TMP/rpm-tmp.8Xjyu0 (%install)

No RPM file created.
```

Reverting the "buildroot" changes made in [this change set](https://github.com/bazelbuild/rules_pkg/commit/ad8f0f2ea79cbf33379b395cc2924cd52660c5ce#diff-1f8cf43b703dccd190e9ba606322f2f5R212) (lines 212-223) appears to resolve this issue. What was the reasoning for those changes? They appear unrelated to the commit message, which is simply replacing abseil with argparse.

**Comment by aiuto** [comment]
My recollection is that the buildroot changes were to make things work, but that is sort of vague.

This doesn't quite make sense to me.
```
install -m 0755 {test.txt} %{buildroot}/etc

%files
/etc/test.txt
```

The syntax {test.txt} is new to me, but seems a basic problem, since we can have many files named test.txt, as long as they are in separate packages. 
Then /etc/test.txt in %files is also weird, because test.txt should either be in /src or /. 

I'll have to make another pass to figure out what is the right path out of this.

**Comment by adruch** [comment]
Currently this issue is a blocker for moving from the builtin pkg_rpm to @rules_pkg. I believe it is also related to #107. 

@aiuto - 
As for the `{test.txt}` syntax, this is what's currently expected by the following code in the rpm.bzl file:

```
    substitutions = {}
    for data_file in ctx.files.data:
        key = "{%s}" % data_file.basename
        substitutions[key] = data_file.path
    ctx.actions.expand_template(
        template = ctx.file.spec_file,
        output = spec_file,
        substitutions = substitutions,
    )
```
Building the substitution key using a different value than basename would be more precise, but would also be more verbose and possibly break backward compatibility.

The example spec file from @apt-itude is what a typical spec file would look like. The %install and %files sections should align (e.g. putting test.txt in /etc in this case). I believe this may also be the issue experienced in Pull Request https://github.com/bazelbuild/rules_pkg/pull/108#issuecomment-547043567.  The `test_rpm.spec` file should have an `%install` section that looks like the example given by @apt-itude above.

**Comment by aiuto** [comment]
This may be fixed by #108

**Comment by aiuto** [comment]
Waiting for verification of fixed at head

**Comment by apt-itude** [comment]
I don't work with Bazel on a regular basis anymore, so I can't comment on whether the issue is resolved. Can you assign to @adruch since they appear to be directly affected by this issue currently?

**Comment by aiuto** [comment]
Friendly ping.  As a heads up, the next major Bazel release will drop the internal pkg_rpm and pkg_deb (maybe not pkg_tar, but that will be soon after).

**Comment by aiuto** [comment]
closing as stale
