### ISSUE TITLE
Support for Windows installers

### ISSUE THREAD

**Issue by ofek** [bazelbuild/rules_pkg#90]
Especially the new MSIX spec, which is the future of Windows packaging

https://docs.microsoft.com/en-us/windows/msix/overview
https://github.com/microsoft/msix-packaging

**Comment by aiuto** [comment]
This is perfect opportunity for a community contribution. Whomever wants to try it should float a proposal for what the rule would look like before doing a complete implementation.

**Comment by ofek** [comment]
Any update on this?

**Comment by aiuto** [comment]
I will happily review someone's proposal about how they will implement it.  I'm even willing to chat with someone who wants to build this and work with them on a design to get their implementation started. I won't have any time to implement this myself in 2022 (and probably 2023).

My rough thoughts on design requirements.
- define toolchains to all the exes.
- start with something easy, like a pkg_cabinet, which would take identical args as pkg_zip, but makes a .CAB file instead.
- considers how you will use `PackageVariablesInfo` in the places where it appropriate to drop things like version numbers into the installer
- is modular enough so that people could reuse the tools to build non-msi installers. For example, building .cab file and signing should be explicit rules.

**Comment by aiuto** [comment]
Closing issues that no one is likely to work on for any forseable future

**Comment by aiuto** [comment]
The concern is that no one from the Bazel team is going to work on this.
Having a backlog of feature requests adds cost to every planning cycle,
even if only to roll them over to the next planning cycle.
